git:
  submodules: false
  quiet: true
  depth: 3
language: python
install:
- pip3 install --upgrade pip
- pip3 install -r requirements.txt
script:
- python3 -m pytest -v || python -m pytest -v
cache: pip
jobs:
  allow_failures:
  - python: 3.8-dev
  include:
  - stage: Tests in Linux
    name: Python 3.8.0 on Xenial Linux
    python: 3.8
  - name: Python 3.8.0 on Bionic Linux
    python: 3.8
    dist: bionic
  - name: Python 3.7.4 on Xenial Linux
    python: 3.7
  - name: Python 3.8 dev on Xenial Linux
    python: 3.8-dev
    script:
    - exit 1
  - stage: Tests in other Platforms
    name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: Python 3.8.0 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version 3.8.0
    - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  - stage: Deploy
    if: "(branch = develop) AND (type = push)"
    python: 3.8
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: H0Ps+8Kwv8UgDXihy2240ZnpNhIwUqOwAz/dv5c2o1RejvpBfgVEVyX/ozUmxC4T8clOhm4JrhMeEa9umNqolyR02VNrD1JkriHvtKP9rosgVIJf7c+k4T+XvNwZ+dwv/wVCnZGwLvvDzCAPDVcwYTJcjEwWCzyZCcx4+Mn5jSKr/mqF4xZ61emkRRfBd51c0Z8JcHO/S/XG1W2xwdH/og026P60Wml8yDw9kYZGNG9XBjJmHjlykS+m6ry0yh2sbP7MxymFgGLEx7nCws74+OhjDqCXMKYjs9sgLt3U3VSh6kQAxd71yWeQygHVYD0vpCWmrvQMzNE7pyNhHhNulKpYGJYmqFmVlRnFdLIYJfTEEVsUe982Qn/evWvIZ2MkOZ+wZ4qh7rMpQP3DX2TtpuAM3l+PECQK0O2tb2YHCHcbDAhSqRXD7FP7zymZqRAf4ii172GZeCPhbPdA/TafPkvnV0BP1Oe2rZFCaEZdm+ZxUG3Qz/YqsXZkTT5d0nuV5xzltLsrYLc+PHOJv3b+n7tVAasBO4OEknFE6Ld9JWrqTQJGVb6bcLE6v0PBJ+JYXAwh3ELK95mRmAx5llwfIuxhZmY2bRxKuJkZAHJZxs/bQE0enkGgn8R4RXtFYQ8dpYx6RD6qaFVl9mDpOce8MoMZwjgioxYpA8syU4hnP+g=
      on:
        branch: develop
      distributions: sdist bdist_wheel
      skip_existing: true