language: python
python:
  - 2.7
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
# command to tests
script:
  # unit test
  - python -m pytest -v
# simple comments testing
